# Created by trellis-cli v0.9.2
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  rootsedu.com:
    site_hosts:
    - canonical: rootsedu.test
      redirects:
      - www.rootsedu.test
    local_path: ../site
    admin_email: admin@rootsedu.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
